### ISSUE TITLE
check command interface to door controller (open/close switch)

### ISSUE THREAD

**Issue by danjl1100** [KevlarSky/TKET-Offeneces#7]
Determine what electrical connection is needed to command the door controller to raise / lower / pause the door  (simulate button press by the user)

## Tasks
- [ ] Determine how the remote sends the "Up/Down" command.  Research "Genie Intellicode" remote (also denoted "Series II controllers" by the controller label)
- [ ] Attempt to recreate the electrical Up/Down command via the terminal blocks on the controller (pictured below)
    - [ ] Alternate, modify the remote to add a parallel input to the hardware switches
    - [ ] Alternate2, modify a wireless remote (pro: less intrusive, con: another battery / radio to power)

## Background
The current "Genie Intellicode" branded control panel has 2 buttons and a red LED indicator:
- Up/Down command button
- Light toggle button
- LED is normally on  (believe it also remains on while sending commands)
This is fed by 2 wires (Push Button, and Common) so it necessarily must have some sort of signaling.

Briefly shorting the "Push Button" terminal to "Common" (COM) did not result in any action by the door controller.  Only saw the red LED indicator briefly extinguish (as I was bypassing its power source).

![Controller_terminals](https://github.com/KevlarSky/TKET-Offeneces/assets/45136864/704ec418-7743-40a0-aba6-3ac095a390be)
![Controller_remote_buttons](https://github.com/KevlarSky/TKET-Offeneces/assets/45136864/8274e5ee-c269-4c8b-8de7-3d8c72945d6c)
